package isirmodels

import "time"

type ISIRRecord struct {
	YearIndicator            string    // 1
	FAFSAUUID                string    // 2
	TransactionUUID          string    // 3
	PersonUUID               string    // 4
	TransactionNumber        int       // 5
	DependencyModel          string    // 6 - const
	ApplicationSource        int       // 7 - enum
	ApplicationReceiptDate   time.Time // 8
	TransactionSource        int       // 9  - enum
	TransactionType          string    // 10 - const
	TransactionLanguage      string    // 11 - const
	TransactionReceiptDate   time.Time // 12
	TransactionProcessedDate time.Time // 13
	TransactionStatus        string    // 14
	RenewalDataUsed          bool      // 15
	FPSCorrectionReason      string    // 16
	SAIChangeFlag            string    // 17
	SAI                      int       // 18
	ProvisionalSAI           int       // 19
	SAIFormula               string    // 20
	SAIComputationType       int       // 21
	MaxPellIndicator         string    // 22
	MinimumPellIndicator     string    // 23
	// 24 skipped, it is filler
	FirstName     string    // 25
	MiddleName    string    // 26
	LastName      string    // 27
	Suffix        string    // 28
	DateOfBirth   time.Time // 29
	SSN           string    // 30
	ITIN          string    // 31
	PhoneNumber   string    // 32
	EmailAddress  string    // 33
	StreetAddress string    // 34
	City          string    // 35
	State         string    // 36
	ZipCode       string    // 37
	Country       string    // 38
	// 39 skipped, it is filler
	MaritalStatus                               string // 40
	GradeLevel                                  string // 41
	FirstBachelorsDegreeBefore2526              string // 42
	PursuingTeacherCertification                string // 43
	ActiveDuty                                  string // 44
	Veteran                                     string // 45
	ChildOrOtherDependents                      string // 46
	ParentsDeceased                             string // 47
	WardOfCourt                                 string // 48
	InFosterCare                                string // 49
	EmancipatedMinor                            string // 50
	LegalGuardianship                           string // 51
	PersonalCircumstancesNoneOfTheAbove         string // 52
	UnaccompaniedHomelessYouthAndSelfSupporting string // 53
	UnaccompaniedHomelessGeneral                string // 54
	UnaccompaniedHomelessHS                     string // 55
	UnaccompaniedHomelessTRIO                   string // 56
	UnaccompaniedHomelessFAA                    string // 57
	StudentHomelessnessNoneOfTheAbove           string // 58
	UnusualCircumstance                         string // 59
	UnsubOnly                                   string // 60
	UpdatedFamilySize                           string // 61
	NumberInCollege                             string // 62
	CitizenshipStatus                           string // 63
	ANumber                                     string // 64
	StateOfLegalResidence                       string // 65
	LegalResidenceDate                          string // 66
	EitherParentAttendCollege                   string // 67
	ParentKilledInTheLineOfDuty                 string // 68
	HighSchoolCompletionStatus                  string // 69
	HighSchoolName                              string // 70
	HighSchoolCity                              string // 71
	HighSchoolState                             string // 72
	HighSchoolEquivalentDiplomaName             string // 73
	HighSchoolEquivalentDiplomaState            string // 74
	ReceivedEITC                                string // 75
	ReceivedFederalHousingAssistance            string // 76
	ReceivedFreeReducedPriceLunch               string // 77
	ReceivedMedicaid                            string // 78
	ReceivedRefundableCreditFor36BHealthPlan    string // 79
	ReceivedSNAP                                string // 80
	ReceivedSupplementalSecurityIncome          string // 81
	ReceivedTANF                                string // 82
	ReceivedWIC                                 string // 83
	FederalBenefitsNoneOfTheAbove               string // 84
	Filed1040Or1040NR                           string // 85
	FiledNonUSTaxReturn                         string // 86
	FiledJointReturnWithCurrentSpouse           string // 87
	TaxReturnFilingStatus                       string // 88
	IncomeEarnedFromWork                        string // 89
	TaxExemptInterestIncome                     string // 90
	UntaxedPortionsOfIRADistributions           string // 91
	IRARollover                                 string // 92
	UntaxedPortionsOfPensions                   string // 93
	PensionRollover                             string // 94
	AdjustedGrossIncome                         string // 95
	IncomeTaxPaid                               string // 96
	EarnedIncomeTaxCreditReceivedDuringTaxYear  string // 97
	DeductiblePaymentsToIRAKeoghOther           string // 98
	EducationCredits                            string // 99
	FiledScheduleABDEFH                         string // 100
	ScheduleCAmount                             string // 101
	CollegeGrantAndScholarshipAid               string // 102
	ForeignEarnedIncomeExclusion                string // 103
	ChildSupportReceived                        string // 104
	TotalOfCashSavingsAndCheckingAccounts       string // 105
	NetWorthOfCurrentInvestments                string // 106
	NetWorthOfBusinessesAndInvestmentFarms      string // 107
	College1                                    string // 108
	College2                                    string // 109
	College3                                    string // 110
	College4                                    string // 111
	College5                                    string // 112
	College6                                    string // 113
	College7                                    string // 114
	College8                                    string // 115
	College9                                    string // 116
	College10                                   string // 117
	College11                                   string // 118
	College12                                   string // 119
	College13                                   string // 120
	College14                                   string // 121
	College15                                   string // 122
	College16                                   string // 123
	College17                                   string // 124
	College18                                   string // 125
	College19                                   string // 126
	College20                                   string // 127
	ConsentToRetrieveAndDiscloseFTI             string // 128
	Signature                                   string // 129
	SignatureDate                               string // 130
	// 131 is filler
	SpouseFirstName                         string // 132
	SpouseMiddleName                        string // 133
	SpouseLastName                          string // 134
	SpouseSuffix                            string // 135
	SpouseDateOfBirth                       string // 136
	SpouseSSN                               string // 137
	SpouseITIN                              string // 138
	SpousePhoneNumber                       string // 139
	SpouseEmailAddress                      string // 140
	SpouseStreetAddress                     string // 141
	SpouseCity                              string // 142
	SpouseState                             string // 143
	SpouseZipCode                           string // 144
	SpouseCountry                           string // 145
	SpouseFiled1040Or1040NR                 string // 146
	SpouseFiledNonUSTaxReturn               string // 147
	SpouseTaxReturnFilingStatus             string // 148
	SpouseIncomeEarnedFromWork              string // 149
	SpouseTaxExemptInterestIncome           string // 150
	SpouseUntaxedPortionsOfIRADistributions string // 151
	SpouseIRARollover                       string // 152
	SpouseUntaxedPortionsOfPensions         string // 153
	SpousePensionRollover                   string // 154
	SpouseAdjustedGrossIncome               string // 155
	SpouseIncomeTaxPaid                     string // 156
	SpouseDeductiblePaymentsToIRAKeoghOther string // 157
	SpouseEducationCredits                  string // 158
	SpouseFiledScheduleABDEFH               string // 159
	SpouseScheduleCAmount                   string // 160
	SpouseForeignEarnedIncomeExclusion      string // 161
	SpouseConsentToRetrieveAndDiscloseFTI   string // 162
	SpouseSignature                         string // 163
	SpouseSignatureDate                     string // 164
	// 165 filler
	ParentFirstName                                  string // 166
	ParentMiddleName                                 string // 167
	ParentLastName                                   string // 168
	ParentSuffix                                     string // 169
	ParentDateOfBirth                                string // 170
	ParentSSN                                        string // 171
	ParentITIN                                       string // 172
	ParentPhoneNumber                                string // 173
	ParentEmailAddress                               string // 174
	ParentStreetAddress                              string // 175
	ParentCity                                       string // 176
	ParentState                                      string // 177
	ParentZipCode                                    string // 178
	ParentCountry                                    string // 179
	ParentMaritalStatus                              string // 180
	ParentStateOfLegalResidence                      string // 181
	ParentLegalResidenceDate                         string // 182
	ParentUpdatedFamilySize                          string // 183
	ParentNumberInCollege                            string // 184
	ParentReceivedEITC                               string // 185
	ParentReceivedFederalHousingAssistance           string // 186
	ParentReceivedFreeReducedPriceLunch              string // 187
	ParentReceivedMedicaid                           string // 188
	ParentReceivedRefundableCreditFor36BHealthPlan   string // 189
	ParentReceivedSNAP                               string // 190
	ParentReceivedSupplementalSecurityIncome         string // 191
	ParentReceivedTANF                               string // 192
	ParentReceivedWIC                                string // 193
	ParentFederalBenefitsNoneOfTheAbove              string // 194
	ParentFiled1040Or1040NR                          string // 195
	ParentFileNonUSTaxReturn                         string // 196
	ParentFiledJointReturnWithCurrentSpouse          string // 197
	ParentTaxReturnFilingStatus                      string // 198
	ParentIncomeEarnedFromWork                       string // 199
	ParentTaxExemptInterestIncome                    string // 200
	ParentUntaxedPortionsOfIRADistributions          string // 201
	ParentIRARollover                                string // 202
	ParentUntaxedPortionsOfPensions                  string // 203
	ParentPensionRollover                            string // 204
	ParentAdjustedGrossIncome                        string // 205
	ParentIncomeTaxPaid                              string // 206
	ParentEarnedIncomeTaxCreditReceivedDuringTaxYear string // 207
	ParentDeductiblePaymentsToIRAKeoghOther          string // 208
	ParentEducationCredits                           string // 209
	ParentFiledScheduleABDEFH                        string // 210
	ParentScheduleCAmount                            string // 211
	ParentCollegeGrantAndScholarshipAid              string // 212
	ParentForeignEarnedIncomeExclusion               string // 213
	ParentChildSupportReceived                       string // 214
	ParentTotalOfCashSavingsAndCheckingAccounts      string // 215
	ParentNetWorthOfCurrentInvestments               string // 216
	ParentNetWorthOfBusinessesAndInvestments         string // 217
	ParentConsentToRetrieveAndDiscloseFTI            string // 218
	ParentSignature                                  string // 219
	ParentSignatureDate                              string // 220
	// 221 Filler
	ParentSpouseFirstName                         string // 222
	ParentSpouseMiddleName                        string // 223
	ParentSpouseLastName                          string // 224
	ParentSpouseSuffix                            string // 225
	ParentSpouseDateOfBirth                       string // 226
	ParentSpouseSSN                               string // 227
	ParentSpouseITIN                              string // 228
	ParentSpousePhoneNumber                       string // 229
	ParentSpouseEmailAddress                      string // 230
	ParentSpouseStreetAddress                     string // 231
	ParentSpouseCity                              string // 232
	ParentSpouseState                             string // 233
	ParentSpouseZipCode                           string // 234
	ParentSpouseCountry                           string // 235
	ParentSpouseFiled1040Or1040NR                 string // 236
	ParentSpouseFileNonUSTaxReturn                string // 237
	ParentSpouseTaxReturnFilingStatus             string // 238
	ParentSpouseIncomeEarnedFromWork              string // 239
	ParentSpouseTaxExemptInterestIncome           string // 240
	ParentSpouseUntaxedPortionsOfIRADistributions string // 241
	ParentSpouseIRARollover                       string // 242
	ParentSpouseUntaxedPortionsOfPensions         string // 243
	ParentSpousePensionRollover                   string // 244
	ParentSpouseAdjustedGrossIncome               string // 245
	ParentSpouseIncomeTaxPaid                     string // 246
	ParentSpouseDeductiblePaymentsToIRAKeoghOther string // 247
	ParentSpouseEducationCredits                  string // 248
	ParentSpouseFiledScheduleABDEFH               string // 249
	ParentSpouseScheduleCAmount                   string // 250
	ParentSpouseForeignEarnedIncomeExclusion      string // 251
	ParentSpouseConsentToRetrieveAndDiscloseFTI   string // 252
	ParentSpouseSignature                         string // 253
	ParentSpouseSignatureDate                     string // 254
	// 255 Filler
	PreparerFirstName     string // 256
	PreparerLastName      string // 257
	PreparerSSN           string // 258
	PreparerEIN           string // 259
	PreparerAffiliation   string // 260
	PreparerStreetAddress string // 261
	PreparerCity          string // 262
	PreparerState         string // 263
	PreparerZipCode       string // 264
	PreparerSignature     string // 265
	PreparerSignatureDate string // 266
	// 267 Filler
	StudentAffirmationStatus                 string // 268
	StudentSpouseAffirmationStatus           string // 269
	ParentAffirmationStatus                  string // 270
	ParentSpouseOrPartnerAffirmationStatus   string // 271
	StudentDateConsentGranted                string // 272
	StudentSpouseDateConsentGranted          string // 273
	ParentDateConsentGranted                 string // 274
	ParentSpouseOrPartnerDateConsentGranted  string // 275
	StudentTransunionMatchStatus             string // 276
	StudentSpouseTransunionMatchStatus       string // 277
	StudentParentTransunionMatchStatus       string // 278
	StudentParentSpouseTransunionMatchStatus string // 279
}
